### PR TITLE
Change 16-21 in story.txt

### PR DESCRIPTION
**Pull request by YSChen0609**
Changed line 16-21 in story.txt and becomes Harsh's version.

### CODE REVIEW

**Comment by YSChen0609** [comment]
@HarshPatel187 
Maybe you can review this and merge this for me please?

**Review by YSChen0609 — COMMENTED** [review]
I made a new commit and tried to create a new PR, but seems that PR sees a branch as a whole!

**Review by kyo330 — APPROVED** [review]
GOOD JOB

**Review by kyo330 — APPROVED** [review]
GOOD JOB!

**Comment by kyo330** [comment]
I have resolved all the conflicts

**Comment by YSChen0609** [comment]
> I have resolved all the conflicts

Nice one!

**Pull request merged**
